# Generated by Django 5.0.2 on 2024-02-13 15:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NameCity',
            fields=[
                ('nc_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nc_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NameStreet',
            fields=[
                ('as_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('as_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NumberApartment',
            fields=[
                ('np_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('np_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='NumberHouse',
            fields=[
                ('nh_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nh_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalData',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('Чоловіча', 'Чоловіча'), ('Жіноча', 'Жіноча')], max_length=255)),
                ('name_city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.namecity')),
                ('name_street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.namestreet')),
                ('number_apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.numberapartment')),
                ('number_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.numberhouse')),
            ],
        ),
    ]
